### ISSUE TITLE
Line does not preserve on generic type assignment

### ISSUE THREAD

**Issue by gusPorter-pl** [Yikes2000/prettier-plugin-preserve-line#1] opened 2024-05-20 11:11 UTC
## Dependency information
"devDependencies": {
  "@changesets/cli": "^2.27.1",
  "@types/dotenv-safe": "^8.1.6",
  "@types/node": "^20.12.7",
  "@yikes2000/prettier-plugin-align-object-properties": "^0.0.2-alpha.2",
  "@yikes2000/prettier-plugin-preserve-line": "^0.0.2-alpha.10",
  "gen-env-types": "^1.3.4",
  "prettier": "^3.2.5",
  "tsup": "^8.0.2",
  "typescript": "^5.4.5"
}

## Steps to reproduce
.prettierrc.js file:
modules.export = {
  plugins: ["@yikes2000/prettier-plugin-align-object-properties", "@yikes2000/prettier-plugin-preserve-line"],
  preserveFirstBlankLine: false,
  preserveLastBlankLine: false,
  preserveDotChain: true
}

The statement I want to put on a multiline:
```
const results = await MyFactory.query<Schema>(schemaQuery).execute();
```

I am forcing the text after `MyFactory` onto a new line, but it reverts.

## The current behavior
The line is preserved like this:
```
const results = await MyFactory.query<Schema>(schemaQuery)
  .execute();
```

If I remove `<Schema>`, it preserves as expected.

## The expected behavior
The line should be preserved like this:
```
const results = await MyFactory
  .query<Schema>(schemaQuery)
  .execute();
```

**Comment by Yikes2000** [comment] 2024-06-21 23:49
Thanks for the report.  That was by design, to require parenthesis on the first line.  However, I will look into relaxing it.

**Comment by Yikes2000** [comment] 2024-06-24 08:05
This issue is fixed in the new plugin: @yikes2000/prettier-plugin-merge-extras

**Comment by Yikes2000** [comment] 2024-06-24 08:05
This issue is fixed in the new plugin: @yikes2000/prettier-plugin-merge-extras

**Closed as completed by Yikes2000** 2024-06-24 08:05 UTC
Labels: bug
